language: python

if: branch = master

jobs:
  include:
    - name: "Linux"
      os: linux
      python: 3.8
      before_install:
        - sudo apt install libsdl2-dev libfreetype6-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev libjpeg-dev libpng-dev libportmidi-dev
        - sudo apt-get build-dep python-pygame
        - sudo apt-get install python-dev
    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - cd test
  - python -m unittest -v TestEntities.py