language: python
python:
  - "3.8"
before_install:
  - sudo apt install libsdl2-dev libfreetype6-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev libjpeg-dev libpng-dev libportmidi-dev
  - sudo apt-get build-dep python-pygame
  - sudo apt-get install python-dev
script:
  - python -m unittest test/TestEntities.py